export default {
	treatementGroups: [
		{ id: 1, name: "whitening" },
		{ id: 2, name: "extraction" },
		{ id: 3, name: "cleaning" },
		{ id: 4, name: "barces" },
	],
	treatements: [
		{ id: 1, group: 1, name: "upper teeth" },
		{ id: 2, group: 1, name: "bottom teeth" },
		{ id: 3, group: 1, name: "full whitening" },
		{ id: 4, group: 1, name: "whitening extra" },
		{ id: 5, group: 2, name: "wisdom teeth" },
		{ id: 6, group: 2, name: "normal teeth" },
		{ id: 7, group: 2, name: "special extraction" },
		{ id: 8, group: 2, name: "some other way" },
		{ id: 9, group: 3, name: "treatement 9" },
		{ id: 10, group: 3, name: "treatement 10" },
		{ id: 11, group: 3, name: "treatement 11" },
		{ id: 12, group: 3, name: "treatement 12" },
		{ id: 13, group: 4, name: "treatement 13" },
		{ id: 14, group: 4, name: "treatement 14" },
		{ id: 15, group: 4, name: "treatement 15" },
		{ id: 16, group: 4, name: "treatement 16" },
	],
	cities: [
		{ id: 1, name: "Istanbul" },
		{ id: 2, name: "Bursa" },
		{ id: 3, name: "Eskishehir" },
		{ id: 4, name: "Kutahya" },
	],
	disctricts: [
		{ id: 1, city: 1, name: "Esenler" },
		{ id: 2, city: 1, name: "Çekmeköy" },
		{ id: 3, city: 1, name: "Fatih" },
		{ id: 4, city: 1, name: "Pendik" },

		{ id: 5, city: 2, name: "Büyükorhan" },
		{ id: 6, city: 2, name: "Gemlik" },
		{ id: 7, city: 2, name: "Gürsu" },
		{ id: 8, city: 2, name: "Harmancik" },

		{ id: 9, city: 3, name: "dÇifteler" },
		{ id: 10, city: 3, name: "Mahmudiye" },
		{ id: 11, city: 3, name: "Beylikova" },
		{ id: 12, city: 3, name: "Sivrihisar" },

		{ id: 12, city: 4, name: "Dumlupinar" },
		{ id: 13, city: 4, name: "Hisarcik" },
		{ id: 14, city: 4, name: "Aslanapa" },
		{ id: 15, city: 4, name: "Tavşanli" },
	],
	clinics: [
		{
			id: 1,
			name: "Ruby Valley Medical Center",
			district: 1,
			language: ["all", "english", "turkish"],
			rating: 5,
		},
		{
			id: 2,
			name: "Southshore Medical Center",
			district: 2,
			language: ["all", "turkish"],
			rating: 4,
		},
		{
			id: 3,
			name: "Pine Rest Medical Clinic",
			district: 3,
			language: ["all", "english", "turkish"],
			rating: 3,
		},
		{
			id: 4,
			name: "The Winter Monkey",
			district: 4,
			language: ["all", "english", "turkish"],
			rating: 4,
		},
		{
			id: 5,
			name: "The Pearl Trumpet",
			district: 5,
			language: ["all", "turkish"],
			rating: 3,
		},
		{
			id: 6,
			name: "The Last Resort",
			district: 6,
			language: ["all", "english", "turkish"],
			rating: 5,
		},
	],
	doctors: [
		{
			id: 1,
			name: "Dr. Ayasun Çilga Alemdar",
			clinic: 1,
			schedule: "",
		},
		{
			id: 2,
			name: "Bayan Üçgül Nurey Gülen Yilmaz",
			clinic: 2,
			schedule: "",
		},
		{
			id: 3,
			name: "Toy Kavurt Akdeniz",
			clinic: 3,
			schedule: "",
		},
		{
			id: 4,
			name: "Bayan Çağlar Ergül Soylu",
			clinic: 4,
			schedule: "",
		},
		{
			id: 5,
			name: "Dr. İçimbike Aslan Soylu",
			clinic: 5,
			schedule: "",
		},
		{
			id: 6,
			name: "Sadat Durdu",
			clinic: 6,
			schedule: "",
		},
	],
};
